services:

 ams2tibber:
  container_name: ams2tibber
  image: zelbanna/ams2tibber:latest
  restart: unless-stopped
  volumes:
   - ams2tibber:/etc/ams2tibber/
  network_mode: host

volumes:
 ams2tibber:
  name: ams2tibber
