services:

 daemon:
  container_name: ams2tibber
  image: zelbanna/ams2tibber:latest
  restart: unless-stopped
  volumes:
   - ams2tibber:/etc/ams2tibber/
  networks:
   infra_net:
    ipv4_address: 172.18.0.80

networks:
 infra_net:
  external: true

volumes:
 ams2tibber:
  name: ams2tibber
